### PR TITLE
Create dlmodels.py

### PR DESCRIPTION
**Pull request by EspioGB**
alternative download model for google colab

### CODE REVIEW

**Comment by TheStingerX** [comment]
what does this do exactly?

**Comment by poiqazwsx** [comment]
I assume downloading things like pretrains and hubert without having to do it manually but you could just copy paste my code if our using on colab

**Comment by TheStingerX** [comment]
@poiqazwsx so this is colab only? also why the theme? i dont see the point.

unless theres something useful im closing.

**Comment by EspioGB** [comment]
sorry about that 😅

**Pull request closed without merging**
