### PR TITLE
add better spectrogram (credits lusbert) 

### PR DESCRIPTION
**Pull request by poiqazwsx**
testing rn

### CODE REVIEW

**Comment by Lusbert** [comment]
on line 1569 and 1570 you have a wrong indentation

**Comment by Lusbert** [comment]
new error yippie
```
Traceback (most recent call last):
  File "D:\Ilaria-RVC-Mainline\infer-web.py", line 11, in <module>
    from infer.modules.uvr5.modules import UVRHANDLER
  File "D:\Ilaria-RVC-Mainline\infer\modules\uvr5\modules.py", line 1, in <module>
    from audio_separator.separator import Separator
ModuleNotFoundError: No module named 'audio_separator'
```

**Comment by Mitsubachi1** [comment]
> new error yippie
> 
> ```
> Traceback (most recent call last):
>   File "D:\Ilaria-RVC-Mainline\infer-web.py", line 11, in <module>
>     from infer.modules.uvr5.modules import UVRHANDLER
>   File "D:\Ilaria-RVC-Mainline\infer\modules\uvr5\modules.py", line 1, in <module>
>     from audio_separator.separator import Separator
> ModuleNotFoundError: No module named 'audio_separator'
> ```

refer to #58

**Comment by poiqazwsx** [comment]
skill based issues

**Comment by poiqazwsx** [comment]
shit should work now

**Comment by TheStingerX** [comment]
line 237, in create_spectrogram_and_get_info
    S = librosa.feature.melspectrogram(y, sr=sr, n_mels=256)
TypeError: melspectrogram() takes 0 positional arguments but 1 positional argument (and 1 keyword-only argument) were given

**Comment by TheStingerX** [comment]
fixed and optimized. 
ready to merge.

**Comment by miqu-s** [comment]
> on line 1569 and 1570 there's also bad indentation should be this instead
> 
> ```python
>                 with gr.Column():
>                     with gr.Row():
>                         inst = gr.Audio(show_download_button=True, interactive=False, label='Instrumental')
>                         vocal = gr.Audio(show_download_button=True, interactive=False, label='Vocals')
>                         UVRBUTTON = gr.Button('Extract')
>                         UVRBUTTON.click(
>                         fn=uvr_handler.uvr,
>                         inputs=[audios],
>                         outputs=[inst, vocal]
>                     )
> ```

Nope, Intended to be like this so audio files are in its own

**Pull request merged**
